Repository cesium/atomic, pull requests merged in 2023-09, with the labels that each got.

#397 refactor: remove sessions
  lib/atomic/activities.ex
  lib/atomic/activities/activity.ex
  lib/atomic/activities/activity_department.ex
  lib/atomic/activities/activity_speaker.ex
  lib/atomic/activities/enrollment.ex
  lib/atomic/activities/session.ex
  lib/atomic/activities/speaker.ex
  lib/atomic/departments.ex
  lib/atomic/organizations/department.ex
  lib/atomic/quantum/certificate_delivery.ex
  lib/atomic/uploaders/post.ex
  lib/atomic_web/components/calendar.ex
  lib/atomic_web/components/calendar/month.ex
  lib/atomic_web/components/calendar/week.ex
  lib/atomic_web/live/activity_live/edit.ex
  lib/atomic_web/live/activity_live/form_component.ex
  lib/atomic_web/live/activity_live/form_component.html.heex
  lib/atomic_web/live/activity_live/index.ex
  lib/atomic_web/live/activity_live/index.html.heex
  lib/atomic_web/live/activity_live/new.ex
  lib/atomic_web/live/activity_live/show.ex
  lib/atomic_web/live/activity_live/show.html.heex
  lib/atomic_web/live/calendar_live/show.ex
  lib/atomic_web/live/calendar_live/show.html.heex
  lib/atomic_web/live/department_live/show.ex
  lib/atomic_web/live/department_live/show.html.heex
  lib/atomic_web/live/home_live/index.ex
  lib/atomic_web/live/home_live/index.html.heex
  lib/atomic_web/live/organization_live/show.ex
  lib/atomic_web/live/organization_live/show.html.heex
  lib/atomic_web/live/scanner_live/index.ex
  lib/atomic_web/views/calendar_utils.ex
  priv/repo/migrations/20221022010100_create_activities.exs
  priv/repo/migrations/20221023200102_create_sessions.exs
  priv/repo/migrations/20221104160002_create_enrollments.exs
  priv/repo/migrations/20221129000958_create_activity_speakers.exs
  priv/repo/migrations/20221129000959_create_activity_departments.exs
  priv/repo/seeds/activities.exs
  test/atomic/activities_test.exs
  test/support/factories/activities_factory.ex
  test/support/fixtures/activities_fixtures.ex
Labels: backend, database

#375 feat: add pagination and table components
  config/config.exs
  lib/atomic/activities.ex
  lib/atomic/activities/activity.ex
  lib/atomic/organizations.ex
  lib/atomic/organizations/membership.ex
  lib/atomic/organizations/organization.ex
  lib/atomic/partnerships.ex
  lib/atomic_web/components/helpers.ex
  lib/atomic_web/components/pagination.ex
  lib/atomic_web/components/table.ex
  lib/atomic_web/live/activity_live/index.ex
  lib/atomic_web/live/activity_live/index.html.heex
  lib/atomic_web/live/membership_live/index.ex
  lib/atomic_web/live/membership_live/index.html.heex
  lib/atomic_web/live/organization_live/index.ex
  lib/atomic_web/live/organization_live/index.html.heex
  lib/atomic_web/live/organization_live/show.ex
  lib/atomic_web/live/partner_live/index.ex
  lib/atomic_web/live/partner_live/index.html.heex
  mix.exs
  mix.lock
Labels: enhancement, frontend, backend

#413 fix: change partnerships to partners
  lib/atomic/organizations/organization.ex
  lib/atomic/organizations/partner.ex
  lib/atomic/partnerships.ex
  lib/atomic_web/live/partner_live/form_component.ex
  lib/atomic_web/live/partner_live/index.ex
  lib/atomic_web/live/partner_live/show.ex
  priv/repo/migrations/20221123000537_create_partnerships.exs
  test/atomic/partnerships_test.exs
  test/support/fixtures/partnerships_fixtures.ex
Labels: bug, backend

#415 feat: add timer to notifications
  assets/tailwind.config.js
  lib/atomic_web/components/notification.ex
  lib/atomic_web/templates/layout/app.html.heex
  lib/atomic_web/templates/layout/live.html.heex
Labels: enhancement, frontend

#418 fix: activity title in week view
  lib/atomic_web/components/calendar/week.ex
Labels: bug, frontend

#402 feat: user settings page
  lib/atomic/accounts.ex
  lib/atomic/accounts/user.ex
  lib/atomic_web/controllers/user_auth.ex
  lib/atomic_web/controllers/user_settings_controller.ex
  lib/atomic_web/controllers/user_setup_controller.ex
  lib/atomic_web/live/membership_live/index.html.heex
  lib/atomic_web/live/profile_live/edit.ex
  lib/atomic_web/live/profile_live/edit.html.heex
  lib/atomic_web/live/profile_live/form_component.ex
  lib/atomic_web/live/profile_live/form_component.html.heex
  lib/atomic_web/live/profile_live/show.ex
  lib/atomic_web/live/profile_live/show.html.heex
  lib/atomic_web/live/user_live/show.html.heex
  lib/atomic_web/router.ex
  lib/atomic_web/templates/layout/live.html.heex
  lib/atomic_web/templates/user_setup/edit.html.heex
  priv/repo/migrations/20221014155230_create_users_auth_tables.exs
  priv/repo/seeds/accounts.exs
  test/atomic/accounts_test.exs
  test/atomic_web/controllers/user_settings_controller_test.exs
  test/support/factories/accounts_factory.ex
Labels: enhancement, frontend, backend

#419 fix: update atomic logo
  lib/atomic_web/live/organization_live/show.html.heex
  lib/atomic_web/templates/layout/live.html.heex
  lib/atomic_web/templates/user_reset_password/new.html.heex
  lib/atomic_web/templates/user_settings/edit.html.heex
  priv/static/images/atomic.png
  priv/static/images/atomic.svg
  priv/static/images/phoenix.png
Labels: enhancement, frontend

#420 fix: function in certificate delivery
  lib/atomic/quantum/certificate_delivery.ex
Labels: bug, backend

#416 fix: security flaw with routes protection
  lib/atomic_web/exceptions.ex
  lib/atomic_web/plugs/verify_association.ex
  lib/atomic_web/router.ex
Labels: bug

#412 fix: problems with platform admin users
  lib/atomic/activities.ex
  lib/atomic/activities/activity.ex
  lib/atomic/activities/activity_department.ex
  lib/atomic/departments.ex
  lib/atomic/organizations/department.ex
  lib/atomic_web/live/activity_live/edit.ex
  lib/atomic_web/live/activity_live/edit.html.heex
  lib/atomic_web/live/activity_live/form_component.ex
  lib/atomic_web/live/activity_live/form_component.html.heex
  lib/atomic_web/live/activity_live/index.ex
  lib/atomic_web/live/activity_live/new.ex
  lib/atomic_web/live/activity_live/show.ex
  lib/atomic_web/live/activity_live/show.html.heex
  lib/atomic_web/live/announcement_live/edit.ex
  lib/atomic_web/live/announcement_live/edit.html.heex
  lib/atomic_web/live/announcement_live/index.ex
  lib/atomic_web/live/announcement_live/show.html.heex
  lib/atomic_web/live/department_live/show.ex
  lib/atomic_web/live/department_live/show.html.heex
  lib/atomic_web/live/scanner_live/index.ex
  lib/atomic_web/router.ex
  priv/repo/migrations/20221022010100_create_activities.exs
  priv/repo/migrations/20221129000959_create_activity_departments.exs
  priv/repo/seeds/activities.exs
  test/support/factories/activities_factory.ex
  test/support/fixtures/activities_fixtures.ex
Labels: bug

#417 refactor: enhance enrollments schema
  lib/atomic/accounts/user.ex
  lib/atomic/activities.ex
  lib/atomic/activities/activity.ex
  lib/atomic/activities/activity_enrollment.ex
  lib/atomic/events/event_enrollment.ex
  lib/atomic/quantum/certificate_delivery.ex
  lib/atomic_web/live/activity_live/show.ex
  priv/repo/migrations/20221104160002_create_activity_enrollments.exs
  priv/repo/migrations/20230914180406_create_event_enrollments.exs
  priv/repo/seeds/activities.exs
  test/atomic/activities_test.exs
  test/support/factories/activities_factory.ex
Labels: enhancement, database

#423 feat: add speakers seeds
  priv/repo/seeds.exs
  priv/repo/seeds/speakers.exs
Labels: enhancement, misc

#421 feat: add toggle password to password fields
  assets/css/app.css
  config/config.exs
  lib/atomic_web.ex
  lib/atomic_web/templates/user_registration/new.html.heex
  lib/atomic_web/templates/user_reset_password/edit.html.heex
  lib/atomic_web/templates/user_session/new.html.heex
Labels: enhancement, frontend

#387 feat(organizations): improve UI & UX
  lib/atomic/organizations.ex
  lib/atomic/organizations/organization.ex
  lib/atomic_web/live/board_live/index.html.heex
  lib/atomic_web/live/organization_live/index.ex
  lib/atomic_web/live/organization_live/index.html.heex
  lib/atomic_web/live/organization_live/show.ex
  lib/atomic_web/live/organization_live/show.html.heex
  priv/fake/organizations.json
  priv/repo/migrations/2022000000000_create_organizations.exs
  priv/repo/seeds/activities.exs
  priv/repo/seeds/organizations.exs
  test/atomic/organizations_test.exs
  test/support/factories/organizations_factory.ex
  test/support/fixtures/organizations_fixtures.ex
Labels: enhancement, frontend
