Repository cesium/atomic, pull requests merged in 2023-08, with the labels that each got.

#313 Fix activities' tabs behavior
  lib/atomic_web/live/activity_live/index.html.heex
Labels: bug, frontend

#315 Create sessions minimum and max entries constraint
  lib/atomic/activities/session.ex
  priv/repo/migrations/20221023200102_create_sessions.exs
  test/support/fixtures/activities_fixtures.ex
Labels: bug, backend

#322 chore: add reviewpad configuration
  reviewpad.yml
Labels: enhancement

#312 fix: seeds
  priv/repo/seeds/activities.exs
  priv/repo/seeds/memberships.exs
  priv/repo/seeds/news.exs
  priv/repo/seeds/organizations.exs
  priv/repo/seeds/partners.exs
  test/support/factories/activities_factory.ex
Labels: bug, database

#328 chore: add license
  LICENSE.txt
Labels: documentation

#321 feat: add user profile
  lib/atomic/accounts.ex
  lib/atomic/accounts/user.ex
  lib/atomic_web/live/membership_live/index.html.heex
  lib/atomic_web/live/user_live/show.ex
  lib/atomic_web/live/user_live/show.html.heex
  lib/atomic_web/router.ex
  lib/atomic_web/templates/layout/live.html.heex
  lib/atomic_web/templates/user_registration/new.html.heex
  priv/repo/migrations/20221014155230_create_users_auth_tables.exs
  priv/repo/seeds/accounts.exs
  test/atomic/accounts_test.exs
  test/support/factories/accounts_factory.ex
Labels: enhancement, frontend, backend

#331 chore: create personalized readme
  CODE_OF_CONDUCT.md
  README.md
Labels: enhancement, documentation

#332 chore: improve contributing
  CONTRIBUTING.md
Labels: enhancement, documentation

#333 fix: improve session number of entries & dates validation
  lib/atomic/activities/session.ex
  priv/repo/migrations/20221023200102_create_sessions.exs
  test/atomic/activities_test.exs
Labels: enhancement, database

#336 feat: add state to partners schema
  lib/atomic/organizations/partner.ex
  priv/repo/migrations/20221123000537_create_partnerships.exs
Labels: enhancement, database

#329 feat: add news related live views
  lib/atomic/news.ex
  lib/atomic/organizations.ex
  lib/atomic/organizations/news.ex
  lib/atomic/organizations/organization.ex
  lib/atomic_web/live/home_live/index.ex
  lib/atomic_web/live/home_live/index.html.heex
  lib/atomic_web/live/news_live/edit.ex
  lib/atomic_web/live/news_live/edit.html.heex
  lib/atomic_web/live/news_live/form_component.ex
  lib/atomic_web/live/news_live/form_component.html.heex
  lib/atomic_web/live/news_live/index.ex
  lib/atomic_web/live/news_live/index.html.heex
  lib/atomic_web/live/news_live/show.ex
  lib/atomic_web/live/news_live/show.html.heex
  lib/atomic_web/router.ex
  priv/repo/seeds/news.exs
  test/support/factories/news_factory.ex
Labels: enhancement, frontend, backend

#337 feat: add cycle to courses schema
  data/courses.txt
  lib/atomic/accounts/course.ex
  priv/repo/migrations/20230325151547_create_courses.exs
Labels: enhancement, database

#341 fix: accounts seeds
  priv/repo/seeds/courses.exs
Labels: bug, database

#326 chore: add credo configuration
  .credo.exs
  mix.exs
  priv/repo/seeds/accounts.exs
  priv/repo/seeds/activities.exs
  priv/repo/seeds/courses.exs
  priv/repo/seeds/departments.exs
  priv/repo/seeds/memberships.exs
  priv/repo/seeds/news.exs
  priv/repo/seeds/organizations.exs
  priv/repo/seeds/partners.exs
Labels: enhancement, misc

#349 fix: seeds
  priv/repo/seeds/activities.exs
  priv/repo/seeds/courses.exs
  priv/repo/seeds/news.exs
Labels: bug, database

#344 refactor: improve time module
  lib/atomic/time.ex
Labels: enhancement, misc

#352 refactor: improve news description display
  lib/atomic_web/live/board_live/new.ex
  lib/atomic_web/live/board_live/new.html.heex
  lib/atomic_web/live/home_live/index.html.heex
  lib/atomic_web/live/news_live/index.html.heex
  lib/atomic_web/router.ex
  lib/atomic_web/views/helpers.ex
  priv/repo/seeds/news.exs
Labels: enhancement, frontend

#357 fix: boards schema name
  lib/atomic/organizations/board.ex
  priv/repo/migrations/20230980102641_create_boards.exs
  priv/repo/migrations/20230980102645_create_board_departments.exs
Labels: bug, database

#318 refactor: schemas, contexts and migrations
  lib/atomic/accounts.ex
  lib/atomic/accounts/user.ex
  lib/atomic/activities.ex
  lib/atomic/activities/activity.ex
  lib/atomic/activities/enrollment.ex
  lib/atomic/activities/location.ex
  lib/atomic/activities/session.ex
  lib/atomic/activities/session_department.ex
  lib/atomic/activities/session_speaker.ex
  lib/atomic/activities/speaker.ex
  lib/atomic/events/enrollment.ex
  lib/atomic/events/event.ex
  lib/atomic/events/event_organization.ex
  lib/atomic/organizations.ex
  lib/atomic/organizations/board.ex
  lib/atomic/organizations/board_departments.ex
  lib/atomic/organizations/card.ex
  lib/atomic/organizations/collaborator.ex
  lib/atomic/organizations/department.ex
  lib/atomic/organizations/membership.ex
  lib/atomic/organizations/organization.ex
  lib/atomic/organizations/partner.ex
  lib/atomic/organizations/users_organizations.ex
  lib/atomic/partnerships.ex
  lib/atomic/quantum/certificate_delivery.ex
  lib/atomic/schema.ex
  lib/atomic/time.ex
  lib/atomic_web/live/activity_live/edit.ex
  lib/atomic_web/live/activity_live/form_component.ex
  lib/atomic_web/live/activity_live/form_component.html.heex
  lib/atomic_web/live/activity_live/new.ex
  lib/atomic_web/live/activity_live/show.ex
  lib/atomic_web/live/activity_live/show.html.heex
  priv/repo/migrations/2022000000000_create_organizations.exs
  priv/repo/migrations/20220922010100_create_events.exs
  priv/repo/migrations/20221000000000_create_departments.exs
  priv/repo/migrations/20221014155230_create_users_auth_tables.exs
  priv/repo/migrations/20221022010100_create_activities.exs
  priv/repo/migrations/20221023200102_create_sessions.exs
  priv/repo/migrations/20221123000537_create_partnerships.exs
  priv/repo/migrations/20221129000955_create_speakers.exs
  priv/repo/migrations/20221129000958_create_session_speakers.exs
  priv/repo/migrations/20221129000959_create_session_departments.exs
  priv/repo/migrations/20221129000961_create_event_organization.exs
  priv/repo/migrations/20230313102641_create_memberships.exs
  priv/repo/migrations/20230325151547_create_courses.exs
  priv/repo/migrations/20230830011755_create_news.exs
  priv/repo/migrations/20230880102641_create_collaborators.exs
  priv/repo/migrations/20230980102641_create_boards.exs
  priv/repo/migrations/20230980102645_create_board_departments.exs
  priv/repo/migrations/20231030141755_create_users_organizations.exs
  priv/repo/seeds/activities.exs
  priv/repo/seeds/memberships.exs
  test/atomic/activities_test.exs
  test/support/factories/activities_factory.ex
  test/support/fixtures/activities_fixtures.ex
Labels: enhancement, bug, backend

#334 chore: upgrade scripts to new version
  scripts/colors.sh
  scripts/execs.sh
  scripts/formatting.sh
  scripts/git.sh
  scripts/helpers.sh
  scripts/import-nodejs-keys
  scripts/logging.sh
  scripts/utils.sh
Labels: enhancement, misc

#345 refactor: create action button component
  lib/atomic_web/components/button.ex
  lib/atomic_web/components/card.ex
  lib/atomic_web/live/department_live/index.ex
  lib/atomic_web/live/department_live/index.html.heex
  lib/atomic_web/live/news_live/index.ex
  lib/atomic_web/live/news_live/index.html.heex
Labels: enhancement, frontend

#361 refactor: change news page to a list
  lib/atomic_web/components/announcement.ex
  lib/atomic_web/live/news_live/index.ex
  lib/atomic_web/live/news_live/index.html.heex
Labels: enhancement, frontend

#327 refactor: improve the way the current academic year is gather
  lib/atomic_web.ex
  lib/atomic_web/components/organizations.ex
  lib/atomic_web/live/activity_live/index.html.heex
  lib/atomic_web/live/activity_live/show.html.heex
  lib/atomic_web/live/board_live/index.ex
  lib/atomic_web/live/department_live/show.html.heex
  lib/atomic_web/live/home_live/index.ex
  lib/atomic_web/live/membership_live/index.ex
  lib/atomic_web/templates/layout/live.html.heex
  lib/atomic_web/views/helpers.ex
  priv/repo/seeds/memberships.exs
  test/atomic/utils_test.exs
  test/atomic_web/helpers_test.exs
  test/support/factories/organizations_factory.ex
Labels: enhancement, backend

#373 feat: add logout option
  lib/atomic_web/config.ex
  lib/atomic_web/router.ex
  lib/atomic_web/templates/layout/live.html.heex
  test/atomic_web/controllers/user_session_controller_test.exs
Labels: enhancement, frontend

#370 fix: enrollments update
  lib/atomic/activities.ex
  lib/atomic/activities/enrollment.ex
Labels: bug, database

#355 feat: create 500 page
  assets/tailwind.config.js
  lib/atomic_web/templates/error/500.html.heex
  test/atomic_web/views/error_view_test.exs
Labels: enhancement, frontend

#372 feat: add years to board index page
  lib/atomic/ecto/year.ex
  lib/atomic_web/live/board_live/index.ex
  lib/atomic_web/live/board_live/index.html.heex
  lib/atomic_web/views/helpers.ex
  priv/repo/seeds/memberships.exs
  test/atomic_web/helpers_test.exs
  test/support/factories/organizations_factory.ex
Labels: enhancement, frontend

#339 fix: show organization page
  lib/atomic/activities.ex
  lib/atomic_web/live/organization_live/show.ex
  lib/atomic_web/live/organization_live/show.html.heex
Labels: enhancement, bug, frontend, backend

#343 refactor: make use of meta programming regarding uploaders
  lib/atomic/organizations/partner.ex
  lib/atomic/uploader.ex
  lib/atomic/uploaders/card.ex
  lib/atomic/uploaders/image.ex
  lib/atomic/uploaders/logo.ex
  lib/atomic/uploaders/partner_image.ex
  lib/atomic/uploaders/post.ex
  lib/atomic/uploaders/profile_picture.ex
Labels: enhancement, misc

#360 feat: improve register flow
  assets/tailwind.config.js
  lib/atomic/accounts.ex
  lib/atomic/accounts/user.ex
  lib/atomic_web/controllers/user_auth.ex
  lib/atomic_web/controllers/user_confirmation_controller.ex
  lib/atomic_web/controllers/user_registration_controller.ex
  lib/atomic_web/controllers/user_session_controller.ex
  lib/atomic_web/controllers/user_setup_controller.ex
  lib/atomic_web/router.ex
  lib/atomic_web/templates/user_confirmation/edit.html.heex
  lib/atomic_web/templates/user_registration/new.html.heex
  lib/atomic_web/templates/user_session/new.html.heex
  lib/atomic_web/templates/user_setup/edit.html.heex
  lib/atomic_web/views/user_setup_view.ex
  priv/repo/migrations/20221014155230_create_users_auth_tables.exs
  priv/static/images/atomic_background.svg
  test/atomic/accounts_test.exs
  test/atomic_web/controllers/user_confirmation_controller_test.exs
  test/atomic_web/controllers/user_session_controller_test.exs
Labels: enhancement

#382 fix: remove small border when user only follow 1 organization
  lib/atomic_web/templates/layout/live.html.heex
Labels: bug, frontend

#376 feat: add followers to organization page
  lib/atomic_web/live/organization_live/show.ex
  lib/atomic_web/live/organization_live/show.html.heex
Labels: enhancement, frontend

#378 feat: cover empty scenarios
  lib/atomic/accounts.ex
  lib/atomic_web/components/empty.ex
  lib/atomic_web/live/activity_live/index.ex
  lib/atomic_web/live/activity_live/index.html.heex
  lib/atomic_web/live/board_live/index.ex
  lib/atomic_web/live/board_live/index.html.heex
  lib/atomic_web/live/department_live/index.ex
  lib/atomic_web/live/department_live/index.html.heex
  lib/atomic_web/live/news_live/index.ex
  lib/atomic_web/live/news_live/index.html.heex
  lib/atomic_web/live/organization_live/index.ex
  lib/atomic_web/live/organization_live/index.html.heex
  lib/atomic_web/live/partner_live/index.ex
  lib/atomic_web/live/partner_live/index.html.heex
  mix.exs
  mix.lock
Labels: enhancement, frontend

#379 feat: schedule news publish time
  lib/atomic/organizations.ex
  lib/atomic/organizations/news.ex
  lib/atomic_web/components/announcement.ex
  lib/atomic_web/live/news_live/form_component.html.heex
  lib/atomic_web/live/news_live/index.ex
  priv/repo/migrations/20230830011755_create_news.exs
  priv/repo/seeds/news.exs
  test/atomic/organizations_test.exs
  test/support/factories/news_factory.ex
  test/support/factory.ex
Labels: enhancement, backend, database

#377 refactor: review when to show "you must login" notification
  lib/atomic_web/controllers/user_auth.ex
  lib/atomic_web/router.ex
  test/atomic_web/controllers/user_auth_test.exs
  test/atomic_web/controllers/user_session_controller_test.exs
Labels: enhancement, frontend, backend

#390 fix: change news name to announcements
  lib/atomic/organizations.ex
  lib/atomic/organizations/news.ex
  lib/atomic/organizations/organization.ex
  lib/atomic_web/components/announcement.ex
  lib/atomic_web/live/announcement_live/edit.ex
  lib/atomic_web/live/announcement_live/edit.html.heex
  lib/atomic_web/live/announcement_live/form_component.ex
  lib/atomic_web/live/announcement_live/form_component.html.heex
  lib/atomic_web/live/announcement_live/index.ex
  lib/atomic_web/live/announcement_live/index.html.heex
  lib/atomic_web/live/announcement_live/show.ex
  lib/atomic_web/live/announcement_live/show.html.heex
  lib/atomic_web/live/home_live/index.ex
  lib/atomic_web/live/home_live/index.html.heex
  lib/atomic_web/live/news_live/edit.html.heex
  lib/atomic_web/live/news_live/form_component.ex
  lib/atomic_web/live/news_live/show.ex
  lib/atomic_web/router.ex
  priv/repo/migrations/20230830011755_create_announcements.exs
  priv/repo/seeds.exs
  priv/repo/seeds/announcements.exs
  test/atomic/organizations_test.exs
  test/support/factories/news_factory.ex
  test/support/factory.ex
Labels: backend

#396 style: add tailwind formatter
  .formatter.exs
  lib/atomic_web/components/announcement.ex
  lib/atomic_web/components/badges.ex
  lib/atomic_web/components/button.ex
  lib/atomic_web/components/calendar.ex
  lib/atomic_web/components/calendar/month.ex
  lib/atomic_web/components/calendar/week.ex
  lib/atomic_web/components/card.ex
  lib/atomic_web/components/empty.ex
  lib/atomic_web/components/organizations.ex
  lib/atomic_web/templates/layout/live.html.heex
  mix.exs
  mix.lock
Labels: enhancement
