Repository cesium/atomic, pull requests merged in 2024-02, with the labels that each got.

#354 feat: add activity forms
  lib/atomic/activities.ex
  lib/atomic/activities/activity.ex
  lib/atomic_web/components/forms.ex
  lib/atomic_web/components/image_uploader.ex
  lib/atomic_web/components/multi_select.ex
  lib/atomic_web/live/activity_live/edit.ex
  lib/atomic_web/live/activity_live/edit.html.heex
  lib/atomic_web/live/activity_live/form_component.ex
  lib/atomic_web/live/activity_live/form_component.html.heex
  lib/atomic_web/live/activity_live/new.html.heex
  priv/repo/seeds/accounts.exs
Labels: frontend

#447 feat: issue templates
  .github/ISSUE_TEMPLATE/0_feature_request.yml
  .github/ISSUE_TEMPLATE/1_bug_report.yml
Labels: enhancement

#456 refactor: redirect when clicking in logo
  lib/atomic_web/templates/layout/live.html.heex
Labels: enhancement

#460 refactor: follow suggestions
  lib/atomic/organizations.ex
  lib/atomic_web/live/home_live/components/follow_suggestions.ex
  lib/atomic_web/live/home_live/components/suggestion.ex
  lib/atomic_web/live/home_live/index.ex
  lib/atomic_web/live/home_live/index.html.heex
Labels: enhancement

#468 feat: tabs component
  lib/atomic_web.ex
  lib/atomic_web/components/tabs.ex
  lib/atomic_web/live/activity_live/index.ex
  lib/atomic_web/live/activity_live/index.html.heex
  lib/atomic_web/live/announcement_live/index.ex
  lib/atomic_web/live/announcement_live/index.html.heex
  lib/atomic_web/live/home_live/index.ex
  lib/atomic_web/live/home_live/index.html.heex
Labels: enhancement, frontend
